version: '3.8'
services:
  postgres:
    image: postgres
    env_file:
      - config/.secrets.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  squish_link_app:
    container_name: squish_link_app
    image: chidinweke/squish_link_app:latest
    build: .
    env_file:
      - config/.secrets.env
    ports:
      - "8080:8080" 
    depends_on:
      - postgres 
volumes:
  postgres-data:

networks:
  default:
      name: app_network 
      external: true
