version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser 
      POSTGRES_DB: mydb     
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  webserver:
    build: .
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
      ROOT_URL: http://localhost:8080/
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    ports:
      - "8080:8080" 
    depends_on:
      - postgres 

volumes:
  postgres-data:
