version: '3.8'
services:
  postgres:
    image: postgres
    networks:
      - app_network
    env_file:
      - config/.secrets.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  squish_link_app:
    container_name: squish_link_app
    build: .
    env_file:
      - config/.secrets.env
    ports:
      - "8080:8080" 
    depends_on:
      - postgres 
    networks:
      - app_network
volumes:
  postgres-data:

networks:
  app_network:
    driver: bridge